[project]
name = "tetris"
version = "0.1.0"
description = "A simple implementation of a tetris solution finder."
readme = "readme.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
